export const themes = {
  midnight: {
    name: 'Midnight',
    description: 'Near-black with white accents',
    colors: {
      bg: '#000000',
      'bg-subtle': '#080808',
      surface: '#0a0a0a',
      'surface-hover': '#141414',
      border: '#1a1a1a',
      text: '#ffffff',
      'text-muted': '#666666',
      accent: '#ffffff',
      'accent-hover': '#e0e0e0',
      'accent-glow': 'rgba(255,255,255,0.06)',
      success: '#00dc82',
      warning: '#f5a623',
      danger: '#ff4444',
    },
  },
  zen: {
    name: 'Zen',
    description: 'Warm, minimal Japanese-inspired aesthetics',
    colors: {
      bg: '#f7f3ee',
      'bg-subtle': '#efe9e1',
      surface: '#ffffff',
      'surface-hover': '#f0ebe4',
      border: '#ddd5ca',
      text: '#2c2420',
      'text-muted': '#8a7e73',
      accent: '#c45d3e',
      'accent-hover': '#b04e32',
      'accent-glow': 'rgba(196,93,62,0.1)',
      success: '#5a8a6a',
      warning: '#c49a3e',
      danger: '#c45d5d',
    },
  },
  nord: {
    name: 'Nord',
    description: 'Cool arctic blues and clean lines',
    colors: {
      bg: '#242933',
      'bg-subtle': '#2e3440',
      surface: '#3b4252',
      'surface-hover': '#434c5e',
      border: '#4c566a',
      text: '#eceff4',
      'text-muted': '#8892a4',
      accent: '#88c0d0',
      'accent-hover': '#7ab4c4',
      'accent-glow': 'rgba(136,192,208,0.15)',
      success: '#a3be8c',
      warning: '#ebcb8b',
      danger: '#bf616a',
    },
  },
  sunset: {
    name: 'Sunset',
    description: 'Warm gradients of amber and violet',
    colors: {
      bg: '#1a0f1e',
      'bg-subtle': '#221528',
      surface: '#2a1b33',
      'surface-hover': '#362342',
      border: '#3d2a4a',
      text: '#f5e6ff',
      'text-muted': '#9a7fb3',
      accent: '#f59e0b',
      'accent-hover': '#d97706',
      'accent-glow': 'rgba(245,158,11,0.15)',
      success: '#86efac',
      warning: '#fcd34d',
      danger: '#fb7185',
    },
  },
  forest: {
    name: 'Forest',
    description: 'Deep greens and organic earth tones',
    colors: {
      bg: '#0c1410',
      'bg-subtle': '#111c16',
      surface: '#16231c',
      'surface-hover': '#1e2e25',
      border: '#253830',
      text: '#dce8e0',
      'text-muted': '#6d8a77',
      accent: '#4ade80',
      'accent-hover': '#22c55e',
      'accent-glow': 'rgba(74,222,128,0.15)',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
  light: {
    name: 'Clean Light',
    description: 'Crisp white with refined accents',
    colors: {
      bg: '#ffffff',
      'bg-subtle': '#fafafa',
      surface: '#f5f5f5',
      'surface-hover': '#eeeeee',
      border: '#e0e0e0',
      text: '#000000',
      'text-muted': '#888888',
      accent: '#000000',
      'accent-hover': '#333333',
      'accent-glow': 'rgba(0,0,0,0.04)',
      success: '#00a860',
      warning: '#c48400',
      danger: '#cc0000',
    },
  },
} as const;

export type ThemeKey = keyof typeof themes | 'system';
export const defaultTheme: ThemeKey = 'system';
export const themeKeys: ThemeKey[] = ['system', ...Object.keys(themes) as (keyof typeof themes)[]];

export const systemThemeEntry = {
  name: 'System',
  description: 'Follows your OS dark/light preference',
  colors: themes.midnight.colors, // preview uses midnight colors
};
