export const themes = {
  midnight: {
    name: 'Midnight',
    description: 'Near-black with white accents',
    colors: {
      bg: '#000000',
      'bg-subtle': '#080808',
      surface: '#0a0a0a',
      'surface-hover': '#141414',
      border: '#1a1a1a',
      text: '#ffffff',
      'text-muted': '#a3a3a3',
      accent: '#ffffff',
      'accent-hover': '#e0e0e0',
      'accent-glow': 'rgba(255,255,255,0.06)',
      success: '#00dc82',
      warning: '#f5a623',
      danger: '#ff4444',
    },
  },
  zen: {
    name: 'Zen',
    description: 'Warm, minimal Japanese-inspired aesthetics',
    colors: {
      bg: '#f7f3ee',
      'bg-subtle': '#efe9e1',
      surface: '#ffffff',
      'surface-hover': '#f0ebe4',
      border: '#ddd5ca',
      text: '#2c2420',
      'text-muted': '#6e6259',
      accent: '#c45d3e',
      'accent-hover': '#b04e32',
      'accent-glow': 'rgba(196,93,62,0.1)',
      success: '#5a8a6a',
      warning: '#c49a3e',
      danger: '#c45d5d',
    },
  },
  nord: {
    name: 'Nord',
    description: 'Cool arctic blues and clean lines',
    colors: {
      bg: '#242933',
      'bg-subtle': '#2e3440',
      surface: '#3b4252',
      'surface-hover': '#434c5e',
      border: '#4c566a',
      text: '#eceff4',
      'text-muted': '#a8b0be',
      accent: '#88c0d0',
      'accent-hover': '#7ab4c4',
      'accent-glow': 'rgba(136,192,208,0.15)',
      success: '#a3be8c',
      warning: '#ebcb8b',
      danger: '#bf616a',
    },
  },
  sunset: {
    name: 'Sunset',
    description: 'Warm gradients of amber and violet',
    colors: {
      bg: '#1a0f1e',
      'bg-subtle': '#221528',
      surface: '#2a1b33',
      'surface-hover': '#362342',
      border: '#3d2a4a',
      text: '#f5e6ff',
      'text-muted': '#c0a8d4',
      accent: '#f59e0b',
      'accent-hover': '#d97706',
      'accent-glow': 'rgba(245,158,11,0.15)',
      success: '#86efac',
      warning: '#fcd34d',
      danger: '#fb7185',
    },
  },
  forest: {
    name: 'Forest',
    description: 'Deep greens and organic earth tones',
    colors: {
      bg: '#0c1410',
      'bg-subtle': '#111c16',
      surface: '#16231c',
      'surface-hover': '#1e2e25',
      border: '#253830',
      text: '#dce8e0',
      'text-muted': '#98b0a0',
      accent: '#4ade80',
      'accent-hover': '#22c55e',
      'accent-glow': 'rgba(74,222,128,0.15)',
      success: '#4ade80',
      warning: '#fbbf24',
      danger: '#f87171',
    },
  },
  light: {
    name: 'Light',
    description: 'Clean light mode inspired by Notion',
    colors: {
      bg: '#ffffff',
      'bg-subtle': '#fbfbfa',
      surface: '#f7f6f3',
      'surface-hover': '#efefed',
      border: '#e3e2de',
      text: '#37352f',
      'text-muted': '#6f6e6b',
      accent: '#2eaadc',
      'accent-hover': '#2898c8',
      'accent-glow': 'rgba(46,170,220,0.08)',
      success: '#4dab9a',
      warning: '#cc8833',
      danger: '#e06c60',
    },
  },
  dark: {
    name: 'Dark',
    description: 'Clean dark mode inspired by Notion',
    colors: {
      bg: '#191919',
      'bg-subtle': '#1e1e1e',
      surface: '#252525',
      'surface-hover': '#2f2f2f',
      border: '#373737',
      text: '#e3e3e3',
      'text-muted': '#b0afac',
      accent: '#529cca',
      'accent-hover': '#4a8db8',
      'accent-glow': 'rgba(82,156,202,0.12)',
      success: '#4dab9a',
      warning: '#cc8833',
      danger: '#e06c60',
    },
  },
} as const;

export type ThemeKey = keyof typeof themes | 'system';
export const defaultTheme: ThemeKey = 'system';
export const themeKeys: ThemeKey[] = ['system', ...Object.keys(themes) as (keyof typeof themes)[]];

export const systemThemeEntry = {
  name: 'System',
  description: 'Follows your OS dark/light preference',
  colors: themes.dark.colors,
};
