config:
  gcp:project: acquired-racer-491202-b4
  gcp:region: europe-west3
  lifeos:dnsProvider: manual
  lifeos:domain: dev.lifeos.zone
  lifeos:dnsZoneProject: lifeos-prod-491301
  lifeos:openclawImageTag: latest
  lifeos:jwtSigningKey: 78a1710deae11f3c62c25e907ab15bd4
  lifeos:convexSiteUrl: https://proper-cormorant-28.eu-west-1.convex.site
  lifeos:gatewaySystemKey: 78a1710deae11f3c62c25e907ab15bd4
  lifeos:gatewayImageName: europe-west3-docker.pkg.dev/acquired-racer-491202-b4/lifeos-dev/ai-gateway:latest
  lifeos:backends:
    - id: "default"
      convexSiteUrl: "https://proper-cormorant-28.eu-west-1.convex.site"
    - id: "kemp"
      convexSiteUrl: "https://calculating-hornet-639.convex.site"
  lifeos:anthropicApiKey:
    secure: v1:DSVq7UyAA3k/vqag:y0+g6MvbXibZkHzzOvBl7L1gTZRSqA7s4MjZ7M+EA89HzpVBFWYhxPyNwtB3A5Y27L2UNXFtN4fEhUwSW5Ir85qkKTertXhV4WYWYya355utFl5Xqod4tIlmvK7CpoMTEaphwiszL65mDV7ITXfEL73dfKHxGfxs/KsiLQ==
encryptionsalt: v1:96XSPyZBR9g=:v1:GNPag+zpFYmZyoy5:qKEEgB5X1r/BEmP8goyew3XzD0ILUw==
