config:
  gcp:project: lifeos-prod-491301
  gcp:region: europe-west3
  lifeos:dnsProvider: cloudDns
  lifeos:domain: lifeos.zone
  lifeos:openclawImageTag: latest
  lifeos:convexSiteUrl: https://charming-squid-23.eu-west-1.convex.site
  lifeos:gatewayImageName: europe-west3-docker.pkg.dev/lifeos-prod-491301/lifeos-prod/ai-gateway:latest
  lifeos:backends:
    - id: "default"
      convexSiteUrl: "https://charming-squid-23.eu-west-1.convex.site"
  lifeos:jwtSigningKey:
    secure: v1:hVJuezUxsTD0iM69:j3qhXqKbcnzNg/ORcciKSE1sXUz8vaEBfpUbAo7c7ief4Q90CLe5FL6jD7hSvVpH
  lifeos:gatewaySystemKey:
    secure: v1:Rfp+wfsSKuyI/j/o:Nh9iZu60wGm2PJtOEP2flMwB9j8vdDDz/g50ciAZO7jq2vxFKg1wc0ICQzLnwuZn
  lifeos:anthropicApiKey:
    secure: v1:2NpfOD9wbzZlAdyq:2RtP6rM8UEoHQAbpBPgEtI1OKC04eM8O2Qm3rAXfVrpU0cgYdYHMM+akyH6Z4ogsG+t8LVed4VkVpyyTZpx4ErnFxcnFCXHl9TgHod2CC72/qne0H9spS1cgsivmIaMz834oo6DAxdEsRKEPInUlXEruTzPs57Nb3+asyw==
encryptionsalt: v1:F+Lr6Wq9yNo=:v1:zh5CqyFmdQce09u7:OUXJzIDTZ+RZdlwaAqeoWI6pPdlUAg==
