// Internal helpers for the Telegram reminder dispatcher. Lives separately
// from `reminderDispatch.ts` because that file uses `"use node";` (needs
// fetch + env access for Telegram), and Node files can only contain
// actions — queries and mutations must stay in the default V8 runtime.

import { v } from "convex/values";
import { internalMutation, internalQuery, mutation } from "./_generated/server";
import { internal } from "./_generated/api";
import { getAuthUserId } from "@convex-dev/auth/server";

export const _findDue = internalQuery({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();
    // Scan via index: pending status, scheduledAt <= now. Bounded at 200
    // per tick — if more reminders pile up, the next tick a minute later
    // will pick them up. We never want a single tick to read unbounded.
    return await ctx.db
      .query("reminders")
      .withIndex("by_status_scheduledAt", (q) =>
        q.eq("status", "pending").lte("scheduledAt", now),
      )
      .take(200);
  },
});

export const _getUserChatId = internalQuery({
  args: { userId: v.id("users") },
  handler: async (ctx, args) => {
    const user = await ctx.db.get(args.userId);
    return user?.telegramChatId ?? null;
  },
});

export const _markDelivered = internalMutation({
  args: { id: v.id("reminders") },
  handler: async (ctx, args) => {
    const existing = await ctx.db.get(args.id);
    if (!existing || existing.status !== "pending") return;
    await ctx.db.patch(args.id, { status: "delivered" });
    await ctx.db.insert("mutationLog", {
      userId: existing.userId,
      action: "deliver",
      tableName: "reminders",
      recordId: args.id,
      beforeData: existing,
      afterData: await ctx.db.get(args.id),
    });
  },
});

export const _setReminderStatus = internalMutation({
  args: { id: v.id("reminders"), status: v.string() },
  handler: async (ctx, args) => {
    const existing = await ctx.db.get(args.id);
    if (!existing) return;
    await ctx.db.patch(args.id, { status: args.status });
    await ctx.db.insert("mutationLog", {
      userId: existing.userId,
      action: "update",
      tableName: "reminders",
      recordId: args.id,
      beforeData: existing,
      afterData: await ctx.db.get(args.id),
    });
  },
});

export const _snoozeReminder = internalMutation({
  args: { id: v.id("reminders"), minutes: v.float64() },
  handler: async (ctx, args) => {
    const existing = await ctx.db.get(args.id);
    if (!existing) return;
    await ctx.db.patch(args.id, {
      scheduledAt: Date.now() + args.minutes * 60_000,
      status: "pending",
      snoozeCount: existing.snoozeCount + 1,
    });
    await ctx.db.insert("mutationLog", {
      userId: existing.userId,
      action: "snooze",
      tableName: "reminders",
      recordId: args.id,
      beforeData: existing,
      afterData: await ctx.db.get(args.id),
    });
  },
});

// ── sendTestTelegram (public mutation) ──────────────
// User-triggered "send me a test reminder right now" — useful to confirm
// the whole pipeline (token + chat ID + webhook reachability) works
// without waiting for a real reminder to come due.
//
// Uses scheduler.runAfter(0) so the actual Telegram fetch happens in a
// Node action; the mutation only validates and returns immediately.
export const sendTestTelegram = mutation({
  args: {},
  handler: async (ctx) => {
    const userId = await getAuthUserId(ctx);
    if (!userId) throw new Error("Not authenticated");

    const user = await ctx.db.get(userId);
    if (!user?.telegramChatId) {
      return { ok: false as const, reason: "no-chat-id" as const };
    }

    await ctx.scheduler.runAfter(0, internal.reminderDispatch.sendTestMessage, {
      chatId: user.telegramChatId,
    });

    return { ok: true as const };
  },
});

// One-time-code helper: when a user types `/start <CODE>` to the bot we
// look up the matching user via their unexpired link code and bind the
// chat ID. The code is generated by the authenticated dashboard
// (`auth.generateTelegramLinkCode`) and stored on `users.telegramLinkCode`
// with an expiry. After successful link, the code is cleared so it can't
// be replayed.
//
// Email-based linking was rejected: anyone who knows your email could
// claim your reminder channel before you do.
export const _claimLinkCode = internalMutation({
  args: { code: v.string(), chatId: v.string() },
  handler: async (ctx, args) => {
    const code = args.code.trim().toUpperCase();
    if (!code) return { ok: false as const, reason: "empty" as const };

    const user = await ctx.db
      .query("users")
      .withIndex("by_telegramLinkCode", (q) => q.eq("telegramLinkCode", code))
      .unique();
    if (!user) return { ok: false as const, reason: "not-found" as const };
    if (!user.telegramLinkExpiresAt || user.telegramLinkExpiresAt < Date.now()) {
      return { ok: false as const, reason: "expired" as const };
    }

    const before = user;
    await ctx.db.patch(user._id, {
      telegramChatId: args.chatId,
      telegramLinkCode: undefined,
      telegramLinkExpiresAt: undefined,
    });

    // Audit the link for traceability.
    await ctx.db.insert("mutationLog", {
      userId: user._id,
      action: "telegram-link",
      tableName: "users",
      recordId: user._id,
      beforeData: before,
      afterData: await ctx.db.get(user._id),
    });

    return { ok: true as const, userId: user._id };
  },
});
