import { defineSchema, defineTable } from "convex/server";
import { authTables } from "@convex-dev/auth/server";
import { v } from "convex/values";

export default defineSchema({
  ...authTables,

  // ── Users (extends authTables.users with our custom fields) ──
  users: defineTable({
    // Convex Auth fields
    email: v.optional(v.string()),
    emailVerificationTime: v.optional(v.float64()),
    image: v.optional(v.string()),
    name: v.optional(v.string()),
    isAnonymous: v.optional(v.boolean()),
    // LifeOS custom fields
    timezone: v.optional(v.string()),
    // Cross-replica lease for OpenAI OAuth token refresh (epoch ms; lock held until this timestamp)
    openaiRefreshLockedUntil: v.optional(v.number()),
    // Telegram delivery — chat ID where reminder messages are sent. Set
    // either via Settings → Integrations (authenticated) or via the
    // bot using `/start <code>` where the code is generated by the
    // logged-in user. Never linked by email — that would let anyone who
    // knows your email hijack reminder delivery.
    telegramChatId: v.optional(v.string()),
    // One-time link code for Telegram pairing. 10-min expiry.
    telegramLinkCode: v.optional(v.string()),
    telegramLinkExpiresAt: v.optional(v.float64()),
    // Granola integration — the API key itself lives in GCP Secret Manager
    // as `byok-{userId}-granola` (same pattern as the Telegram bot token).
    // We only stamp connection + sync timestamps here so the dashboard can
    // render status without a Secret Manager round-trip on every render.
    granolaConnectedAt: v.optional(v.float64()),
    granolaSyncedAt: v.optional(v.float64()),
    granolaSyncError: v.optional(v.string()),
    // Google Workspace (Calendar) — OAuth tokens live in GCP Secret
    // Manager as `byok-{userId}-google-calendar` (JSON blob with
    // access_token / refresh_token / expires_at_ms). These fields are
    // just metadata for the dashboard to render connection status.
    googleCalendarConnectedAt: v.optional(v.float64()),
    googleCalendarEmail: v.optional(v.string()), // which Google account they authorised
    googleCalendarSyncedAt: v.optional(v.float64()),
    googleCalendarSyncError: v.optional(v.string()),
    // Last time the weekly-review Telegram prompt was sent. Used to
    // dedupe if/when the cron switches from once-per-week to per-tz
    // hourly polling — the row carries forward week to week.
    weeklyReviewPromptedAt: v.optional(v.float64()),
  }).index("email", ["email"])
    .index("by_telegramLinkCode", ["telegramLinkCode"]),

  // ── API Keys ───────────────────────────────────────
  apiKeys: defineTable({
    userId: v.id("users"),
    keyPrefix: v.string(),
    keyHash: v.string(),
    name: v.optional(v.string()),
    lastUsedAt: v.optional(v.float64()),
  }).index("by_userId", ["userId"])
    .index("by_keyPrefix", ["keyPrefix"]),

  // ── Tasks ──────────────────────────────────────────
  tasks: defineTable({
    userId: v.id("users"),
    title: v.string(),
    notes: v.optional(v.string()),
    status: v.string(), // "todo" | "done" | "dropped"
    dueDate: v.optional(v.string()), // "YYYY-MM-DD"
    projectId: v.optional(v.id("projects")),
    goalId: v.optional(v.id("goals")),
    position: v.float64(),
    completedAt: v.optional(v.float64()),
    updatedAt: v.float64(),
  }).index("by_userId_status", ["userId", "status"])
    .index("by_userId_dueDate", ["userId", "dueDate"])
    .index("by_userId", ["userId"]),

  // ── Projects ───────────────────────────────────────
  projects: defineTable({
    userId: v.id("users"),
    title: v.string(),
    description: v.optional(v.string()),
    status: v.string(), // "active" | "completed" | "archived"
    // Dan Sullivan's Impact Filter — optional one-pager that forces clarity
    // before delegation. successCriteria intentionally has no length cap in
    // the validator; the wizard enforces "exactly 8" at the UI layer.
    impactFilter: v.optional(v.object({
      purpose: v.string(),
      importance: v.string(),
      idealOutcome: v.string(),
      worstResult: v.string(),
      bestResult: v.string(),
      successCriteria: v.array(v.string()),
      who: v.optional(v.string()),
      completedAt: v.float64(),
      updatedAt: v.float64(),
    })),
  }).index("by_userId", ["userId"])
    .index("by_userId_status", ["userId", "status"]),

  // ── Goals ──────────────────────────────────────────
  goals: defineTable({
    userId: v.id("users"),
    title: v.string(),
    description: v.optional(v.string()),
    purpose: v.optional(v.string()), // RPM "why" — the deeper reason this goal matters
    status: v.string(), // "active" | "completed" | "dropped"
    targetDate: v.optional(v.string()),
    quarter: v.optional(v.string()), // "2026-Q1"
    completedAt: v.optional(v.float64()),
  }).index("by_userId", ["userId"])
    .index("by_userId_status", ["userId", "status"]),

  // ── Identity (one per user) ────────────────────────
  identity: defineTable({
    userId: v.id("users"),
    statement: v.string(),     // "I am a builder who ships fast..."
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"]),

  // ── Vision Board ─────────────────────────────────
  visionBoard: defineTable({
    userId: v.id("users"),
    imageUrl: v.string(),      // URL or Convex storage ID
    caption: v.optional(v.string()),
    position: v.float64(),     // for ordering
  }).index("by_userId", ["userId"]),

  // ── Journals ───────────────────────────────────────
  journals: defineTable({
    userId: v.id("users"),
    entryDate: v.string(), // "YYYY-MM-DD"
    mit: v.optional(v.string()),
    p1: v.optional(v.string()),
    p2: v.optional(v.string()),
    notes: v.optional(v.string()),
    wins: v.array(v.string()),
    // Phase 2 — Section 7I additions
    summary: v.optional(v.string()),         // one-line "headline" of the day
    mood: v.optional(v.float64()),            // 1-5 (Daylio scale)
    gratitudes: v.optional(v.array(v.string())),
    updatedAt: v.float64(),
  }).index("by_userId_entryDate", ["userId", "entryDate"]),

  // ── Day Plans ──────────────────────────────────────
  dayPlans: defineTable({
    userId: v.id("users"),
    planDate: v.string(), // "YYYY-MM-DD"
    wakeTime: v.optional(v.string()), // "07:00"
    schedule: v.array(v.object({
      start: v.string(),
      end: v.string(),
      label: v.string(),
      type: v.string(),
      taskId: v.optional(v.string()),
      // Block-level done state for items that aren't backed by a task
      // (habits like "shower", "wake up"). Task-backed blocks derive
      // done-ness from `tasks.status === "done"` — don't duplicate it
      // here.
      done: v.optional(v.boolean()),
    })),
    overflow: v.array(v.string()),
    mitTaskId: v.optional(v.id("tasks")),
    p1TaskId: v.optional(v.id("tasks")),
    p2TaskId: v.optional(v.id("tasks")),
    mitDone: v.boolean(),
    p1Done: v.boolean(),
    p2Done: v.boolean(),
  }).index("by_userId_planDate", ["userId", "planDate"]),

  // ── Weekly Plans ───────────────────────────────────
  weeklyPlans: defineTable({
    userId: v.id("users"),
    weekStart: v.string(), // "YYYY-MM-DD" (Monday)
    theme: v.optional(v.string()),
    goals: v.array(v.object({
      title: v.string(),
      status: v.optional(v.string()),
      goalId: v.optional(v.string()),
    })),
    reviewScore: v.optional(v.float64()),
  }).index("by_userId_weekStart", ["userId", "weekStart"]),

  // ── Ideas ──────────────────────────────────────────
  ideas: defineTable({
    userId: v.id("users"),
    content: v.string(),
    actionability: v.optional(v.string()), // "high" | "medium" | "low"
    nextStep: v.optional(v.string()),
    projectId: v.optional(v.id("projects")),
    // Phase 2 — Section 12B+ addition: mark as reviewed
    reviewedAt: v.optional(v.float64()),
  }).index("by_userId", ["userId"]),

  // ── Thoughts ───────────────────────────────────────
  thoughts: defineTable({
    userId: v.id("users"),
    content: v.string(),
    title: v.optional(v.string()),
  }).index("by_userId", ["userId"]),

  // ── Wins ───────────────────────────────────────────
  wins: defineTable({
    userId: v.id("users"),
    content: v.string(),
    entryDate: v.string(), // "YYYY-MM-DD"
  }).index("by_userId", ["userId"])
    .index("by_userId_entryDate", ["userId", "entryDate"]),

  // ── Resources ──────────────────────────────────────
  resources: defineTable({
    userId: v.id("users"),
    title: v.string(),
    url: v.optional(v.string()),
    content: v.optional(v.string()),
    type: v.optional(v.string()), // "article" | "tool" | "book" | "video" | "other"
    tags: v.optional(v.array(v.string())),
  }).index("by_userId", ["userId"]),

  // ── Reviews ────────────────────────────────────────
  reviews: defineTable({
    userId: v.id("users"),
    reviewType: v.string(), // "daily" | "weekly" | "monthly" | "quarterly"
    periodStart: v.string(),
    periodEnd: v.string(),
    content: v.any(),
    score: v.optional(v.float64()),
  }).index("by_userId", ["userId"]),

  // ── Reminders ──────────────────────────────────────
  reminders: defineTable({
    userId: v.id("users"),
    title: v.string(),
    body: v.optional(v.string()),
    scheduledAt: v.float64(), // epoch ms
    status: v.string(), // "pending" | "delivered" | "snoozed" | "done"
    snoozeCount: v.float64(),
  }).index("by_userId", ["userId"])
    .index("by_userId_status", ["userId", "status"])
    // The dispatcher cron polls "pending" reminders ordered by scheduledAt.
    // This index lets us scan only the pending tail instead of the full table.
    .index("by_status_scheduledAt", ["status", "scheduledAt"]),

  // ── Finance: categories ────────────────────────────
  // Per-user taxonomy. Seeded with the 13 defaults (Food & Dining,
  // Transport, …) on first finance interaction. `isIncome` flips the sign
  // convention used in reports — categories like Salary roll up as income,
  // everything else as spend.
  financeCategories: defineTable({
    userId: v.id("users"),
    name: v.string(),
    color: v.string(),         // hex, "#aabbcc"
    isIncome: v.boolean(),
    isDefault: v.optional(v.boolean()),
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"]),

  // ── Finance: statements ────────────────────────────
  // One row per CSV upload. `parsedCount` is rows successfully imported
  // (after dedup — duplicates against earlier uploads aren't counted).
  financeStatements: defineTable({
    userId: v.id("users"),
    source: v.string(),            // "revolut" | "wio" | "generic"
    filename: v.string(),
    accountLabel: v.optional(v.string()),
    uploadedAt: v.float64(),
    parsedCount: v.float64(),
    skippedCount: v.float64(),
  }).index("by_userId", ["userId"]),

  // ── Finance: transactions ──────────────────────────
  // Signed amounts in the original currency (negative = debit/spend).
  // `amountUsd` is the cached USD conversion at the transaction date,
  // populated at import time via the fxRates table. `externalId` is a
  // deterministic hash of source-specific stable fields so re-uploads
  // dedupe (Revolut: date|desc|amount|currency|fee, WIO: ref number).
  financeTransactions: defineTable({
    userId: v.id("users"),
    statementId: v.optional(v.id("financeStatements")),
    externalId: v.string(),
    date: v.string(),              // "YYYY-MM-DD"
    description: v.string(),
    descriptionRaw: v.optional(v.string()),
    merchantRaw: v.optional(v.string()),
    amount: v.float64(),           // signed, original currency
    currency: v.string(),
    amountUsd: v.optional(v.float64()),
    fee: v.optional(v.float64()),
    direction: v.optional(v.string()),  // "debit" | "credit"
    categoryId: v.optional(v.id("financeCategories")),
    status: v.string(),            // "uncategorized" | "categorized" | "excluded"
    source: v.string(),            // "revolut" | "wio" | "generic"
    isIncome: v.boolean(),         // mirror of resolved category, cached
    suggestedCategoryId: v.optional(v.id("financeCategories")),
    suggestionConfidence: v.optional(v.float64()),
    suggestionSource: v.optional(v.string()), // "memory" | "llm"
    updatedAt: v.float64(),
  })
    .index("by_userId", ["userId"])
    .index("by_userId_status", ["userId", "status"])
    .index("by_userId_date", ["userId", "date"])
    .index("by_userId_externalId", ["userId", "externalId"]),

  // ── Finance: merchant memory ───────────────────────
  // Learning table: when a user categorises a merchant the mapping is
  // stamped here so future transactions for the same merchant get an
  // instant suggestion (no LLM call needed).
  merchantCategoryMemory: defineTable({
    userId: v.id("users"),
    merchantKey: v.string(),       // lowercased + collapsed-whitespace
    categoryId: v.id("financeCategories"),
    usageCount: v.float64(),
    lastUsedAt: v.float64(),
  }).index("by_userId_merchantKey", ["userId", "merchantKey"]),

  // ── Finance: FX rates ──────────────────────────────
  // Cached daily rates (currency → USD) from Frankfurter (ECB). Lookup is
  // (date, currency); values are immutable for a given date so no upsert
  // on conflict is needed — only insert.
  fxRates: defineTable({
    date: v.string(),              // "YYYY-MM-DD"
    currency: v.string(),
    rateToUsd: v.float64(),
    source: v.string(),            // "frankfurter" | "manual" | …
  }).index("by_date_currency", ["date", "currency"]),

  // ── Meetings ───────────────────────────────────────
  // Synced from Granola via the Personal API. The transcript is stored as a
  // pre-joined string (speaker-prefixed) instead of an array of segments —
  // Convex docs cap at 1MB and the join keeps us well below for typical
  // meeting lengths. If a meeting exceeds the cap we truncate at sync time
  // and stamp `transcriptTruncated`.
  meetings: defineTable({
    userId: v.id("users"),
    granolaId: v.string(),                 // "not_xxx" from Granola
    title: v.string(),
    summary: v.optional(v.string()),         // AI-generated overview (Granola's `summary_text` — plain)
    summaryMarkdown: v.optional(v.string()), // markdown variant (Granola's `summary_markdown` — has bullets + headings)
    transcript: v.optional(v.string()),    // pre-joined, speaker-prefixed
    transcriptTruncated: v.optional(v.boolean()),
    attendees: v.optional(v.array(v.string())),
    startedAt: v.optional(v.float64()),    // epoch ms — when the meeting happened
    endedAt: v.optional(v.float64()),
    granolaUrl: v.optional(v.string()),
    // Folders the note belongs to in Granola, plus any user-added LifeOS tags.
    // Granola's `folder_membership[]` may contain multiple folders for one note.
    folders: v.optional(v.array(v.string())),
    tags: v.optional(v.array(v.string())),
    // Detail-fetch tracking — list returns metadata only; detail (with
    // transcript/summary/attendees/calendar_event) is a per-note GET.
    // We stamp `detailFetchedAt` so a re-sync can skip already-detailed
    // notes that haven't been updated upstream.
    detailFetchedAt: v.optional(v.float64()),
    granolaUpdatedAt: v.optional(v.float64()), // epoch ms from Granola's `updated_at`
    syncedAt: v.float64(),
  })
    .index("by_userId", ["userId"])
    .index("by_userId_startedAt", ["userId", "startedAt"])
    .index("by_userId_granolaId", ["userId", "granolaId"]),

  // ── Upcoming meetings ──────────────────────────────
  // Mirror of a calendar event from Google (eventually) or a manually-added
  // entry. While Google Workspace integration is gated, `source: "mock"`
  // rows seeded via `upcomingMeetings.seedMock` keep the UI useful for
  // testing. When Google connects, sync just upserts the same shape with
  // `source: "google"` and `externalId` set to the GCal event id.
  upcomingMeetings: defineTable({
    userId: v.id("users"),
    source: v.string(),                    // "google" | "manual" | "mock"
    externalId: v.optional(v.string()),    // GCal event id when source="google"
    title: v.string(),
    description: v.optional(v.string()),
    startedAt: v.float64(),                // epoch ms
    endedAt: v.float64(),
    attendees: v.array(v.string()),        // names or emails — matches `meetings.attendees` shape
    location: v.optional(v.string()),
    htmlLink: v.optional(v.string()),
    updatedAt: v.float64(),
  })
    .index("by_userId", ["userId"])
    .index("by_userId_startedAt", ["userId", "startedAt"])
    .index("by_userId_externalId", ["userId", "externalId"]),

  // ── Google OAuth state (CSRF) ──────────────────────
  // Short-lived state tokens generated when a user initiates the Google
  // Calendar OAuth flow, verified on the callback to prevent CSRF. Rows
  // are deleted on successful exchange and expired rows are cleaned by
  // the daily cron.
  googleOAuthStates: defineTable({
    userId: v.id("users"),
    state: v.string(),
    expiresAt: v.float64(),
  }).index("by_state", ["state"])
    .index("by_userId", ["userId"]),

  // ── Google Calendar sync cursor ────────────────────
  // Stores the per-user syncToken so the hourly sync only pulls events
  // that changed since the last run. `timeMin`/`timeMax` filters aren't
  // compatible with syncToken, so we drop back to a 30-day window on
  // full resyncs (token expired or first connect).
  googleCalendarSyncState: defineTable({
    userId: v.id("users"),
    calendarId: v.string(), // "primary" or specific calendar id
    syncToken: v.optional(v.string()),
    lastFullSyncAt: v.optional(v.float64()),
  }).index("by_userId", ["userId"]),

  // ── Meeting preps ──────────────────────────────────
  // One-pager linked to an upcoming meeting. Auto-discovers past meetings
  // with overlapping attendees + open tasks mentioning them; the user
  // edits agenda + notes; an LLM generates suggested talking points from
  // the gathered context. Each upcoming meeting can have at most one prep.
  meetingPreps: defineTable({
    userId: v.id("users"),
    upcomingMeetingId: v.id("upcomingMeetings"),
    title: v.string(),                            // copied from upcoming for offline reading
    agenda: v.optional(v.string()),               // user-editable markdown
    notes: v.optional(v.string()),                // user-editable scratch
    talkingPoints: v.optional(v.string()),        // LLM-generated markdown
    talkingPointsSource: v.optional(v.string()),  // "openai" | "manual" — for future BYOK swap
    // Auto-discovered context — refreshed on demand via `refreshContext`.
    relatedMeetingIds: v.array(v.id("meetings")),
    relatedTaskIds: v.array(v.id("tasks")),
    relatedGoalIds: v.array(v.id("goals")),
    contextRefreshedAt: v.optional(v.float64()),
    updatedAt: v.float64(),
  })
    .index("by_userId", ["userId"])
    .index("by_upcomingMeetingId", ["upcomingMeetingId"]),

  // ── Workouts ────────────────────────────────────────
  workouts: defineTable({
    userId: v.id("users"),
    workoutDate: v.string(), // "YYYY-MM-DD"
    type: v.string(), // "strength" | "cardio" | "mobility" | "sport" | "other"
    title: v.string(),
    durationMinutes: v.optional(v.float64()),
    exercises: v.optional(v.array(v.object({
      name: v.string(),
      sets: v.optional(v.float64()),
      reps: v.optional(v.float64()),
      weight: v.optional(v.float64()),
      unit: v.optional(v.string()), // "kg" | "lbs"
    }))),
    notes: v.optional(v.string()),
    programmeId: v.optional(v.id("programmes")),
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"])
    .index("by_userId_workoutDate", ["userId", "workoutDate"]),

  // ── Programmes ─────────────────────────────────────
  programmes: defineTable({
    userId: v.id("users"),
    title: v.string(),
    description: v.optional(v.string()),
    status: v.string(), // "active" | "completed" | "archived"
    startDate: v.string(), // "YYYY-MM-DD"
    endDate: v.optional(v.string()), // "YYYY-MM-DD"
    notes: v.optional(v.string()),
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"])
    .index("by_userId_status", ["userId", "status"]),

  // ── Food Log ────────────────────────────────────────
  foodLog: defineTable({
    userId: v.id("users"),
    entryDate: v.string(), // "YYYY-MM-DD"
    name: v.string(), // "Chicken breast", "Oatmeal", etc.
    mealType: v.optional(v.string()), // "breakfast" | "lunch" | "dinner" | "snack"
    calories: v.optional(v.float64()),
    protein: v.optional(v.float64()), // grams
    carbs: v.optional(v.float64()), // grams
    fat: v.optional(v.float64()), // grams
    quantity: v.optional(v.string()), // "200g", "1 cup", etc.
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"])
    .index("by_userId_entryDate", ["userId", "entryDate"]),

  // ── Macro Goals ────────────────────────────────────
  macroGoals: defineTable({
    userId: v.id("users"),
    calories: v.float64(),
    protein: v.float64(), // grams
    carbs: v.float64(), // grams
    fat: v.float64(), // grams
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"]),

  // ── User Profile (onboarding personalization) ──────
  userProfile: defineTable({
    userId: v.id("users"),
    displayName: v.optional(v.string()),
    role: v.optional(v.string()),
    topGoals: v.optional(v.array(v.string())),
    focusAreas: v.optional(v.array(v.string())),
    communicationTone: v.optional(v.string()),
    workSchedule: v.optional(v.string()),
    // Multi-select in the UI ("most people share 2-3"). Union accepts the
    // legacy string form so existing rows stamped before this fix still
    // read; new writes use the array form.
    biggestChallenge: v.optional(v.union(v.string(), v.array(v.string()))),
    accountabilityStyle: v.optional(v.string()),
    selectedUseCases: v.optional(v.array(v.string())),
    setupPath: v.optional(v.string()),
    setupCompleted: v.optional(v.boolean()),
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"]),

  // ── Dashboard Config ───────────────────────────────
  dashboardConfig: defineTable({
    userId: v.id("users"),
    navMode: v.string(),           // "sidebar" | "header"
    navOrder: v.array(v.string()),
    navHidden: v.array(v.string()),
    pagePresets: v.any(),          // { today: "solopreneur", ideas: "content-creator", ... }
    customTheme: v.optional(v.any()), // custom color overrides
  }).index("by_userId", ["userId"]),

  // ── Skills ─────────────────────────────────────────
  // Per-user skill manifests adapted from Garry Tan's "skillify" pattern.
  // Each skill is a markdown rulebook the Life Coach reads on every turn so
  // it knows when to use a deterministic CLI command instead of asking the
  // LLM to guess. Example: "always run `lifeos meeting list --search X`
  // before answering a question about meetings."
  //
  // Skills are user-owned so each LifeOS user can customise their agent.
  // The `enabled` flag lets the user toggle a skill off without deleting it.
  skills: defineTable({
    userId: v.id("users"),
    name: v.string(),                 // short slug, e.g. "meeting-recall"
    summary: v.string(),              // one-line description for the index
    body: v.string(),                 // markdown body — rules + example commands
    triggers: v.optional(v.array(v.string())), // keyword hints for the resolver
    enabled: v.boolean(),
    updatedAt: v.float64(),
  }).index("by_userId", ["userId"])
    .index("by_userId_name", ["userId", "name"]),

  // ── Mutation Log ───────────────────────────────────
  mutationLog: defineTable({
    userId: v.id("users"),
    action: v.string(),
    tableName: v.string(),
    recordId: v.string(), // stringified Convex ID
    beforeData: v.optional(v.any()),
    afterData: v.optional(v.any()),
  }).index("by_userId", ["userId"]),

  // ═══════════════════════════════════════════════════════
  // Hosted deployment tables (ported from ClawNow)
  // ═══════════════════════════════════════════════════════

  // ── Balances ─────────────────────────────────────────
  balances: defineTable({
    userId: v.id("users"),
    amount: v.number(), // cents
  }).index("by_userId", ["userId"]),

  // ── Subscriptions ────────────────────────────────────
  subscriptions: defineTable({
    userId: v.id("users"),
    stripeSubscriptionId: v.string(),
    stripePriceId: v.string(),
    planType: v.union(
      v.literal("dashboard"),
      v.literal("byok"),
      v.literal("basic"),
      v.literal("standard"),
      v.literal("pro"),
      v.literal("premium"),
    ),
    status: v.union(
      v.literal("active"),
      v.literal("past_due"),
      v.literal("canceled"),
      v.literal("unpaid"),
    ),
    currentPeriodEnd: v.number(),
    cancelAtPeriodEnd: v.boolean(),
    includedCreditsCents: v.number(),
    createdAt: v.number(),
    lastUpdatedAt: v.number(),
  })
    .index("by_userId", ["userId"])
    .index("by_stripeSubscriptionId", ["stripeSubscriptionId"]),

  // ── Deployment Settings (ClawNow's "userSettings") ───
  deploymentSettings: defineTable({
    userId: v.id("users"),
    apiKeySource: v.union(v.literal("ours"), v.literal("byok")),
    anthropicAuthMethod: v.optional(
      v.union(v.literal("api_key"), v.literal("setup_token")),
    ),
    anthropicKeyLength: v.optional(v.number()),
    openaiAuthMethod: v.optional(
      v.union(v.literal("api_key"), v.literal("chatgpt_oauth")),
    ),
    openaiKeyLength: v.optional(v.number()),
    googleKeyLength: v.optional(v.number()),
    moonshotKeyLength: v.optional(v.number()),
    minimaxKeyLength: v.optional(v.number()),
    telegramBotTokenLength: v.optional(v.number()),
    discordBotTokenLength: v.optional(v.number()),
    selectedModel: v.optional(v.string()),
    pendingDeploy: v.optional(v.boolean()),
    customEnvKeys: v.optional(v.array(v.object({ name: v.string(), valueLength: v.number() }))),
  }).index("by_userId", ["userId"]),

  // ── Deployments ──────────────────────────────────────
  deployments: defineTable({
    userId: v.id("users"),
    subdomain: v.string(),
    gatewayToken: v.string(),
    podSecret: v.string(),
    callbackJwt: v.string(),
    status: v.union(
      v.literal("provisioning"),
      v.literal("starting"),
      v.literal("running"),
      v.literal("error"),
      v.literal("deactivating"),
      v.literal("deactivated"),
      v.literal("suspended"),
    ),
    configHash: v.string(),
    targetImageTag: v.string(),
    podIp: v.optional(v.string()),
    errorMessage: v.optional(v.string()),
    deactivatedAt: v.optional(v.number()),
    pvcRetainUntil: v.optional(v.number()),
    createdAt: v.number(),
    lastUpdatedAt: v.number(),
  })
    .index("by_userId", ["userId"])
    .index("by_subdomain", ["subdomain"])
    .index("by_podSecret", ["podSecret"])
    .index("by_status", ["status"]),

  // ── Coupons ──────────────────────────────────────────
  coupons: defineTable({
    code: v.string(),
    creditAmountCents: v.number(),
    maxUses: v.number(),
    currentUses: v.number(),
    expiresAt: v.optional(v.number()),
    description: v.optional(v.string()),
    createdAt: v.number(),
  }).index("by_code", ["code"]),

  // ── Coupon Redemptions ───────────────────────────────
  couponRedemptions: defineTable({
    couponId: v.id("coupons"),
    userId: v.id("users"),
    creditAmountCents: v.number(),
    redeemedAt: v.number(),
  })
    .index("by_couponId_userId", ["couponId", "userId"])
    .index("by_userId", ["userId"]),
});
